# Generated by Django 5.1.1 on 2024-09-22 19:00

import django.db.models.deletion
import django_ansible_inventory.fields
import django_ansible_inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnsibleGroupTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_ansible_inventory.fields.UpperCharField(
                        max_length=100, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansible Group Tag",
                "verbose_name_plural": "Ansible Group Tags",
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("business_unit", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Business Unit",
                "verbose_name_plural": "Business Units",
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("environment", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Environment",
                "verbose_name_plural": "Environments",
            },
        ),
        migrations.CreateModel(
            name="HostClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("host_class", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Host Class",
                "verbose_name_plural": "Host Classes",
            },
        ),
        migrations.CreateModel(
            name="HostStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("host_status", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Host Status",
                "verbose_name_plural": "Host Status",
            },
        ),
        migrations.CreateModel(
            name="HostType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("host_type", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Host Type",
                "verbose_name_plural": "Host Types",
            },
        ),
        migrations.CreateModel(
            name="NetworkLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Description, e.g., vlan100",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        help_text="IP network in CIDR notation, e.g., 172.16.0.0/23",
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Name",
                "verbose_name_plural": "Network Names",
            },
        ),
        migrations.CreateModel(
            name="Purpose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("purpose", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Purpose",
                "verbose_name_plural": "Purpose",
            },
        ),
        migrations.CreateModel(
            name="SupportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("group", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Support Group",
                "verbose_name_plural": "Support Groups",
            },
        ),
        migrations.CreateModel(
            name="SupportLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_default",
                    models.BooleanField(
                        default=False,
                        help_text="Sets the default that will be used in forms.",
                        verbose_name="Default",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enables or Disables item.",
                        verbose_name="Enabled",
                    ),
                ),
                (
                    "deprecated",
                    models.BooleanField(
                        default=False,
                        help_text="Item should no longer be used.",
                        verbose_name="Deprecated",
                    ),
                ),
                ("level", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Support Levels",
                "verbose_name_plural": "Support Levelss",
            },
        ),
        migrations.CreateModel(
            name="AnsibleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_ansible_inventory.fields.LowerCharField(
                        max_length=100, unique=True
                    ),
                ),
                ("group_vars", models.JSONField(blank=True, default=dict)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="groups",
                        to="django_ansible_inventory.ansiblegrouptag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ansible Group",
                "verbose_name_plural": "Ansible Groups",
            },
        ),
        migrations.CreateModel(
            name="NetworkAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("is_assigned", models.BooleanField(default=False)),
                (
                    "network_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.networklabel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network Address",
                "verbose_name_plural": "Network Addresses",
            },
        ),
        migrations.CreateModel(
            name="Host",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django_ansible_inventory.fields.LowerCharField(max_length=255),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("host_vars", models.JSONField(blank=True, default=dict)),
                ("short_description", models.CharField(max_length=255)),
                (
                    "business_unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.businessunit",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        default=django_ansible_inventory.models.get_default_environment,
                        limit_choices_to={"enabled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.environment",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="hosts", to="django_ansible_inventory.ansiblegroup"
                    ),
                ),
                (
                    "host_class",
                    models.ForeignKey(
                        default=django_ansible_inventory.models.get_default_hostclass,
                        limit_choices_to={"enabled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.hostclass",
                    ),
                ),
                (
                    "host_status",
                    models.ForeignKey(
                        default=django_ansible_inventory.models.get_default_hoststatus,
                        limit_choices_to={"enabled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.hoststatus",
                    ),
                ),
                (
                    "host_type",
                    models.ForeignKey(
                        default=django_ansible_inventory.models.get_default_hosttype,
                        limit_choices_to={"enabled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.hosttype",
                    ),
                ),
                (
                    "ip_address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_ansible_inventory.networkaddress",
                    ),
                ),
                (
                    "vlan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="django_ansible_inventory.networklabel",
                    ),
                ),
                (
                    "purpose",
                    models.ForeignKey(
                        default=django_ansible_inventory.models.get_default_purpose,
                        limit_choices_to={"enabled": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.purpose",
                    ),
                ),
                (
                    "support_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.supportgroup",
                    ),
                ),
                (
                    "support_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_ansible_inventory.supportlevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Host",
                "verbose_name_plural": "Hosts",
            },
        ),
    ]
