# Generated by Django 5.1.1 on 2024-09-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_ansible_inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networklabel",
            options={
                "verbose_name": "Network Label",
                "verbose_name_plural": "Network Labels",
            },
        ),
        migrations.AlterModelOptions(
            name="supportlevel",
            options={
                "verbose_name": "Support Levels",
                "verbose_name_plural": "Support Levels",
            },
        ),
        migrations.AlterField(
            model_name="host",
            name="short_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
